apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: simple-job-container
        image: busybox
        command: ["echo", "Hi harun ganteng"]
      restartPolicy: Never
