apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev-environment
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
